config/routes.rb
Cloudconnectdemo::Application.routes.draw do
  devise_for :rails_users

  root :to => 'salesforce#accounts'
  match '/accounts' => 'salesforce#accounts'
  match '/account/:id' => 'salesforce#account'
  match '/contacts' => 'salesforce#contacts'

end

app/models/account.rb
class Account < SalesforceModel
  self.table_name =  ENV['HEROKUCONNECT_SCHEMA'] + '.account'

  has_many :contacts, :primary_key => "sfid", :foreign_key => "accountid"

  attr_protected :CreatedDate, :SystemModstamp, :LastModifiedDate
end

app/models/contact.rb
class Contact < SalesforceModel
  self.table_name =  ENV['HEROKUCONNECT_SCHEMA'] + '.contact'
  belongs_to :account, :primary_key => 'sfid', :foreign_key => 'accountid'

  attr_protected :createddate, :systemmodstamp, :lastmodifieddate
end

app/models/lead.rb
class Lead < SalesforceModel
  self.table_name =  'lead__c'
end

app/models/opportunity.rb
 class Opportunity < SalesforceModel
  self.table_name =  'opportunity'

  attr_protected :CreatedDate, :SystemModstamp, :LastModifiedDate
end

app/models/rails_user.rb
class RailsUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  # attr_accessible :title, :body

  belongs_to :contact
  belongs_to :lead

  def self.match_contact_by_email(email)
  	Contact.find_by_email(email)
  end

  def self.match_lead_by_email(email)
  	Lead.find_by_email(email)
  end

  def salesforce_name
  	if self.contact
  		"#{self.contact.firstname} #{self.contact.lastname}"
  	elsif self.lead
  		"#{self.lead.firstname} #{self.lead.lastname}"
  	else
  		""
  	end
  end

  def salesforce_id
  	self.contact ? self.contact.sfid : (self.lead ? self.lead.sfid : nil)
  end

  def sf_error
  	if self.contact
  		self.contact.cc_last_error
  	elsif self.lead
  		self.lead.cc_last_error
  	end
  end
  
  def after_confirmation
  	if self.contact.nil? && self.lead.nil?
  		puts "No associated contact or lead"
  		self.contact = RailsUser.match_contact_by_email(self.email)
  		if self.contact.nil?
  			self.lead = RailsUser.match_lead_by_email(self.email)
  		end
  		if self.contact.nil? && self.lead.nil?
  			puts "Create a new lead"
  			# Create a new Lead for this user
  			self.lead = Lead.create(:email => self.email)
  		end
  		save()
  	end
  end

end

app/models/salesforce_model.rb
class SalesforceModel < ActiveRecord::Base
    self.abstract_class = true
    self.inheritance_column = 'rails_type'

    if ENV['HEROKUCONNECT_URL'].nil?
    	puts "WARNING: YOU SHOULD SET HEROKUCONNECT_URL IN YOUR ENVIRONMENT"
    end
    if ENV['HEROKUCONNECT_SCHEMA'].nil?
    	puts "WARNING: YOU SHOULD SET HEROKUCONNECT_SCHEMA IN YOUR ENVIRONMENT"
    end

    establish_connection ENV['HEROKUCONNECT_URL']
	attr_protected :createddate, :systemmodstamp, :lastmodifieddate

	def hc_errors
		HerokuconnectTriggerLog.where(:record_id => self.id, :state => 'FAILED').order("id DESC").all	
	end	

	def hc_last_error
		errs = cc_errors()
		if errs[0]
			errs[0].sf_message
		else
			nil
		end
	end
end

class HerokuconnectTriggerLog < SalesforceModel
	self.table_name = '_trigger_log'

	def self.pending
		HerokuconnectTriggerLog.where(:state => 'NEW').count
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery
  	
	before_filter :authenticate_rails_user!

end

app/controllers/salesforce_controller.rb
class SalesforceController < ApplicationController

  def accounts
    @page = (params[:page] || 1).to_i
    @accounts = Account.order("name").offset(@page*20).limit(20).all()
  end

  def account
    if params[:id] =~ /^\d+$/
        @account = Account.find(params[:id])
    else
        @account = Account.find_by_sfid(params[:id])
    end

    begin
      @contacts = @account.contacts
    rescue
      @contacts = []
    end
  end

  def contacts
    @page = (params[:page] || 1).to_i
    @contacts = Contact.order("lastname").offset(@page*20).limit(20).all()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudconnectdemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <style>
        .tab {
            padding:6px;
            border-left:1px solid #CCC;
            border-right:1px solid #CCC;
            border-top:1px solid #DDD;
            border-bottom: 1px solid #666;
            float:left;
        }
    </style>

</head>
<body>
<% if rails_user_signed_in? %>
  Welcome <%= current_rails_user.salesforce_name %> (<%= current_rails_user.salesforce_id %> <%= current_rails_user.sf_error %>)
  <li>
  <%= link_to('Logout', destroy_rails_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_rails_user_session_path)  %>  
  </li>
<% end %>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<h1 style="width:100%;text-align:right;border:1px solid #CCC">cloudconnect Rails Demo</h1>

<div class="tab"><%= link_to 'Accounts', '/accounts' %></div>
<div class="tab"><%= link_to 'Contacts', '/contacts' %></div>
<div style="clear:both"></div>

<%= yield %>

</body>
</html>

app/views/salesforce/account.html.erb
<h1>Account: <%= @account.name %></h1>

<h2>Contacts</h2>
<table border="1">
    <tr>
        <th>id</th><th>Name</th><th>Email</th><th>Phone</th>
    </tr>
    <% @contacts.each do |contact| %>
      <% next if contact.nil? %>
      <tr>
          <td><%= contact.id %></td>
          <td><%= contact.firstname %> <%= contact.lastname %></td>
          <td><%= contact.email %></td>
          <td><%= contact.phone %></td>
      </tr>
    <% end %>
</table>

app/views/salesforce/accounts.html.erb
<h1>Salesforce Accounts</h1>
<table>
    <tr>
        <th>Name</th><th>Date</th><th>Salesforce Id</th>
    </tr>
    <% @accounts.each do |account| %>
    <tr>
        <td><%= account.name %></td>
        <td><%= account.createddate.strftime("%d %b %y") %></td>
        <td><%= account.sfid %></td>
        <td><%= link_to "details", "/account/#{account.id}" %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'prev', {:page => @page-1} %> |
<%= link_to 'next', {:page => @page+1} %>

app/views/salesforce/contacts.html.erb
<h1>Salesforce Contacts</h1>
<table>
    <tr>
        <th>Name</th><th>Date</th><th>Salesforce Id</th>
    </tr>
    <% @contacts.each do |contact| %>
    <tr>
        <td><%= contact.firstname %> <%= contact.lastname %></td>
        <td><%= contact.createddate.strftime("%d %b %y") %></td>
        <td><%= contact.sfid %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'prev', {:page => @page-1} %> |
<%= link_to 'next', {:page => @page+1} %>